logging:
  level:
    com.baomidou.dynamic: debug 
spring:
  datasource:
    dynamic:
      #primary: db1 #设置默认的数据源或者数据源组,默认值即为master
      #strict: false #设置严格模式,默认false不启动. 启动后再为匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        multimodule:
          jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT
          #driver-class-name: com.mysql.jdbc.Driver
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
          hikari: 
            auto-commit: true
            connection-test-query: SELECT 1
            connection-timeout: 15000
            idle-timeout: 30000
            max-lifetime: 900000
            maximum-pool-size: 15
            minimum-idle: 5